var QR = [
  {
    "Theme": "Transports",
    "Question": "Faut-il agrandir l'aéroport de Nice?",
    "Reponse": "Oui",
    "Benoit Kandel": -1,
    "Valéry Sohm": 0,
    "Christian Estrosi": 2,
    "Patrick Allemand": -2,
    "Philippe Vardon": -1,
    "Jean-Marc Governatori": -2,
    "Mireille Damiano": -2,
  },
  {
    "Theme": "Transports",
    "Question": "Faut-il agrandir l'aéroport de Nice?",
    "Reponse": "Non",
    "Benoit Kandel": 1,
    "Valéry Sohm": 0,
    "Christian Estrosi": -2,
    "Patrick Allemand": 2,
    "Philippe Vardon": 1,
    "Jean-Marc Governatori": 2,
    "Mireille Damiano": 2,
  },
  {
    "Theme": "Transports",
    "Question": "Il faut plus de places de stationnement pour les voitures en centre ville",
    "Reponse": "Oui",
    "Benoit Kandel": 2,
    "Valéry Sohm": 2,
    "Christian Estrosi": 0,
    "Patrick Allemand": -1,
    "Philippe Vardon": 2,
    "Jean-Marc Governatori": -2,
    "Mireille Damiano": -2,
  },
  {
    "Theme": "Transports",
    "Question": "Il faut plus de places de stationnement pour les voitures en centre ville",
    "Reponse": "Non",
    "Benoit Kandel": -2,
    "Valéry Sohm": -2,
    "Christian Estrosi": 0,
    "Patrick Allemand": 1,
    "Philippe Vardon": -2,
    "Jean-Marc Governatori": 2,
    "Mireille Damiano": 2,
  },
  {
    "Theme": "Transports",
    "Question": "Faut-il prolonger la ligne de tram 1 jusqu'à l'Ariane et la Trinité ?",
    "Reponse": "Oui",
    "Benoit Kandel": -2,
    "Valéry Sohm": 0,
    "Christian Estrosi": -2,
    "Patrick Allemand": 2,
    "Philippe Vardon": -2,
    "Jean-Marc Governatori": 2,
    "Mireille Damiano": 2,
  },
  {
    "Theme": "Transports",
    "Question": "Faut-il prolonger la ligne de tram 1 jusqu'à l'Ariane et la Trinité ?",
    "Reponse": "Non",
    "Benoit Kandel": 2,
    "Valéry Sohm": 0,
    "Christian Estrosi": 2,
    "Patrick Allemand": -2,
    "Philippe Vardon": 2,
    "Jean-Marc Governatori": -2,
    "Mireille Damiano": -2,
  },
  {
    "Theme": "Transports",
    "Question": "Les transports doivent-ils être rendus gratuits pour...",
    "Reponse": "...les jeunes",
    "Benoit Kandel": -2,
    "Valéry Sohm": -2,
    "Christian Estrosi": 1,
    "Patrick Allemand": 2,
    "Philippe Vardon": -2,
    "Jean-Marc Governatori": 1,
    "Mireille Damiano": 2,
  },
   {
    "Theme": "Transports",
    "Question": "Les transports doivent-ils être rendus gratuits pour...",
    "Reponse": "...les seniors",
    "Benoit Kandel": -2,
    "Valéry Sohm": -2,
    "Christian Estrosi": -1,
    "Patrick Allemand": 2,
    "Philippe Vardon": -2,
    "Jean-Marc Governatori": 1,
    "Mireille Damiano": 2,
  },
   {
    "Theme": "Transports",
    "Question": "Les transports doivent-ils être rendus gratuits pour...",
    "Reponse": "... tout le monde",
    "Benoit Kandel": -2,
    "Valéry Sohm": -2,
    "Christian Estrosi": -2,
    "Patrick Allemand": 2,
    "Philippe Vardon": -2,
    "Jean-Marc Governatori": 1,
    "Mireille Damiano": 2,
  },
   {
    "Theme": "Transports",
    "Question": "Les transports doivent-ils être rendus gratuits pour...",
    "Reponse": "Non, ils doivent rester payants",
    "Benoit Kandel": 2,
    "Valéry Sohm": 2,
    "Christian Estrosi": -1,
    "Patrick Allemand": -2,
    "Philippe Vardon": 2,
    "Jean-Marc Governatori": -1,
    "Mireille Damiano": -2,
  },
  {
    "Theme": "Transports",
    "Question": "Le service de vélos en libre service \"vélo bleu\" doit-il être étendu à tous les quartiers?",
    "Reponse": "Oui",
    "Benoit Kandel": -2,
    "Valéry Sohm": -1,
    "Christian Estrosi": -2,
    "Patrick Allemand": 2,
    "Philippe Vardon": -2,
    "Jean-Marc Governatori": 2,
    "Mireille Damiano": 2,
  },
  {
    "Theme": "Transports",
    "Question": "Le service de vélos en libre service \"vélo bleu\" doit-il être étendu à tous les quartiers?",
    "Reponse": "Non",
    "Benoit Kandel": 2,
    "Valéry Sohm": 1,
    "Christian Estrosi": 2,
    "Patrick Allemand": -2,
    "Philippe Vardon": 2,
    "Jean-Marc Governatori": -2,
    "Mireille Damiano": -2,
  },
  {
    "Theme": "Transports",
    "Question": "Faut-il mettre en place une navette maritime pour relier Nice à Monaco ?",
    "Reponse": "Non",
    "Benoit Kandel": 0,
    "Valéry Sohm": 0,
    "Christian Estrosi": 0,
    "Patrick Allemand": -2,
    "Philippe Vardon": 0,
    "Jean-Marc Governatori": 2,
    "Mireille Damiano": 0,
  },
  {
    "Theme": "Transports",
    "Question": "Faut-il mettre en place une navette maritime pour relier Nice à Monaco ?",
    "Reponse": "Oui",
    "Benoit Kandel": 0,
    "Valéry Sohm": 0,
    "Christian Estrosi": 0,
    "Patrick Allemand": 2,
    "Philippe Vardon": 0,
    "Jean-Marc Governatori": 2,
    "Mireille Damiano": 0,
  },
  {
    "Theme": "Sécurité",
    "Question": "Doit-on faire entrer les nouvelles technologies dans le dispositif sécurité de Nice ?",
    "Reponse": "Oui",
    "Benoit Kandel": 0,
    "Valéry Sohm": 0,
    "Christian Estrosi": 2,
    "Patrick Allemand": -2,
    "Philippe Vardon": 0,
    "Jean-Marc Governatori": 0,
    "Mireille Damiano": -2,
  },
  {
    "Theme": "Sécurité",
    "Question": "Doit-on faire entrer les nouvelles technologies dans le dispositif sécurité de Nice ?",
    "Reponse": "Non",
    "Benoit Kandel": 0,
    "Valéry Sohm": 0,
    "Christian Estrosi": -2,
    "Patrick Allemand": 2,
    "Philippe Vardon": 0,
    "Jean-Marc Governatori": 0,
    "Mireille Damiano": 2,
  },
  {
    "Theme": "Sécurité",
    "Question": "Faut-il augmenter le nombre d'agents de police municipale sur le terrain?",
    "Reponse": "Oui",
    "Benoit Kandel": 2,
    "Valéry Sohm": 0,
    "Christian Estrosi": 1,
    "Patrick Allemand": 1,
    "Philippe Vardon": 2,
    "Jean-Marc Governatori": 1,
    "Mireille Damiano": 0,
  },
  {
    "Theme": "Sécurité",
    "Question": "Faut-il augmenter le nombre d'agents de police municipale sur le terrain?",
    "Reponse": "Non",
    "Benoit Kandel": -2,
    "Valéry Sohm": 0,
    "Christian Estrosi": -1,
    "Patrick Allemand": -1,
    "Philippe Vardon": -2,
    "Jean-Marc Governatori": -1,
    "Mireille Damiano": 0,
  },
  {
    "Theme": "Environnement",
    "Question": "Faut-il détruire l'Acropolis et le TNL pour prolonger la promenade du Paillon?",
    "Reponse": "Oui",
    "Benoit Kandel": -2,
    "Valéry Sohm": -2,
    "Christian Estrosi": 2,
    "Patrick Allemand": -2,
    "Philippe Vardon": -2,
    "Jean-Marc Governatori": -2,
    "Mireille Damiano": -2,
  },
  {
    "Theme": "Environnement",
    "Question": "Faut-il détruire l'Acropolis et le TNL pour prolonger la promenade du Paillon?",
    "Reponse": "Non",
    "Benoit Kandel": 2,
    "Valéry Sohm": 2,
    "Christian Estrosi": -2,
    "Patrick Allemand": 2,
    "Philippe Vardon": 2,
    "Jean-Marc Governatori": 2,
    "Mireille Damiano": 2,
  },
  {
    "Theme": "Environnement",
    "Question": "Faut-il renforcer les sanctions contre les incivilités (dépôts sauvages, mégots, etc)?",
    "Reponse": "Oui",
    "Benoit Kandel": 2,
    "Valéry Sohm": 2,
    "Christian Estrosi": 2,
    "Patrick Allemand": -1,
    "Philippe Vardon": 0,
    "Jean-Marc Governatori": 0,
    "Mireille Damiano": -1,
  },
  {
    "Theme": "Environnement",
    "Question": "Faut-il renforcer les sanctions contre les incivilités (dépôts sauvages, mégots, etc)?",
    "Reponse": "Non",
    "Benoit Kandel": 2,
    "Valéry Sohm": 0,
    "Christian Estrosi": 2,
    "Patrick Allemand": 1,
    "Philippe Vardon": 0,
    "Jean-Marc Governatori": 0,
    "Mireille Damiano": 1,
  },
  {
    "Theme": "Environnement",
    "Question": "Faut-il interdire les animaux sauvages dans les cirques ?",
    "Reponse": "Oui",
    "Benoit Kandel": 2,
    "Valéry Sohm": 0,
    "Christian Estrosi": 2,
    "Patrick Allemand": 0,
    "Philippe Vardon": 2,
    "Jean-Marc Governatori": 2,
    "Mireille Damiano": 0,
  },
  {
    "Theme": "Environnement",
    "Question": "Faut-il interdire les animaux sauvages dans les cirques ?",
    "Reponse": "Non",
    "Benoit Kandel": -2,
    "Valéry Sohm": 0,
    "Christian Estrosi": -2,
    "Patrick Allemand": 0,
    "Philippe Vardon": -2,
    "Jean-Marc Governatori": -2,
    "Mireille Damiano": 0,
  },
  {
    "Theme": "Finances",
    "Question": "En matière de finances, faut-il ...",
    "Reponse": "Réduire la dette",
    "Benoit Kandel": 2,
    "Valéry Sohm": 2,
    "Christian Estrosi": 0,
    "Patrick Allemand": 1,
    "Philippe Vardon": 2,
    "Jean-Marc Governatori": 1,
    "Mireille Damiano": 1,
  },
  {
    "Theme": "Sports et Loisirs",
    "Question": "En matière de finances, faut-il ...",
    "Reponse": "Continuer à emprunter",
    "Benoit Kandel": 0,
    "Valéry Sohm": 0,
    "Christian Estrosi": 2,
    "Patrick Allemand": 0,
    "Philippe Vardon": -2,
    "Jean-Marc Governatori": 0,
    "Mireille Damiano": 0,
  },
  {
    "Theme": "Sports et Loisirs",
    "Question": "En matière de finances, faut-il ...",
    "Reponse": "Augmenter les impôts",
    "Benoit Kandel": -2,
    "Valéry Sohm": -2,
    "Christian Estrosi": 0,
    "Patrick Allemand": 0,
    "Philippe Vardon": -2,
    "Jean-Marc Governatori": 0,
    "Mireille Damiano": 0,
  },
  {
    "Theme": "Environnement",
    "Question": "Faut-il sanctuariser la plaine du Var et arrêter toutes les constructions?",
    "Reponse": "Oui",
    "Benoit Kandel": 2,
    "Valéry Sohm": 2,
    "Christian Estrosi": -2,
    "Patrick Allemand": 2,
    "Philippe Vardon": 2,
    "Jean-Marc Governatori": 2,
    "Mireille Damiano": 2,
  },
  {
    "Theme": "Environnement",
    "Question": "Faut-il sanctuariser la plaine du Var et arrêter toutes les constructions?",
    "Reponse": "Non",
    "Benoit Kandel": -2,
    "Valéry Sohm": -2,
    "Christian Estrosi": 2,
    "Patrick Allemand": -2,
    "Philippe Vardon": -2,
    "Jean-Marc Governatori": -2,
    "Mireille Damiano": -2,
  },
  {
    "Theme": "Sécurité",
    "Question": "Le dispositif de vidéo-surveillance dans la rue doit-il être maintenu ?",
    "Reponse": "Oui",
    "Benoit Kandel": 1,
    "Valéry Sohm": 0,
    "Christian Estrosi": 2,
    "Patrick Allemand": -1,
    "Philippe Vardon": 1,
    "Jean-Marc Governatori": -2,
    "Mireille Damiano": -2,
  },
  {
    "Theme": "Sécurité",
    "Question": "Le dispositif de vidéo-surveillance dans la rue doit-il être maintenu ?",
    "Reponse": "Non",
    "Benoit Kandel": 0,
    "Valéry Sohm": 0,
    "Christian Estrosi": -2,
    "Patrick Allemand": 1,
    "Philippe Vardon": 0,
    "Jean-Marc Governatori": 2,
    "Mireille Damiano": 2,
  },
  {
    "Theme": "Finances",
    "Question": "Le nouvel impôt métropolitain sur le foncier doit être...",
    "Reponse": "Supprimé",
    "Benoit Kandel": 2,
    "Valéry Sohm": 2,
    "Christian Estrosi": -2,
    "Patrick Allemand": 1,
    "Philippe Vardon": 2,
    "Jean-Marc Governatori": 0,
    "Mireille Damiano": 0,
  },
    {
    "Theme": "Finances",
    "Question": "Le nouvel impôt métropolitain sur le foncier doit être...",
    "Reponse": "Maintenu",
    "Benoit Kandel": -2,
    "Valéry Sohm": -2,
    "Christian Estrosi": 2,
    "Patrick Allemand": -1,
    "Philippe Vardon": -2,
    "Jean-Marc Governatori": 0,
    "Mireille Damiano": 0,
  },
  {
    "Theme": "Environnement",
    "Question": "La promenade des anglais doit-elle etre piétonne un dimanche par mois?",
    "Reponse": "Oui",
    "Benoit Kandel": -2,
    "Valéry Sohm": -2,
    "Christian Estrosi": 2,
    "Patrick Allemand": 2,
    "Philippe Vardon": -2,
    "Jean-Marc Governatori": 2,
    "Mireille Damiano": 2,
  },
  {
    "Theme": "Environnement",
    "Question": "La promenade des anglais doit-elle etre piétonne un dimanche par mois?",
    "Reponse": "Non",
    "Benoit Kandel": 0,
    "Valéry Sohm": 2,
    "Christian Estrosi": -2,
    "Patrick Allemand": -2,
    "Philippe Vardon": 2,
    "Jean-Marc Governatori": -2,
    "Mireille Damiano": -2,
  },
  {
    "Theme": "Environnement",
    "Question": "Quelle est la priorité pour améliorer l'environnement ?",
    "Reponse": "planter des centaines de milliers d'arbres",
    "Benoit Kandel": -1,
    "Valéry Sohm": 0,
    "Christian Estrosi": 2,
    "Patrick Allemand": 0,
    "Philippe Vardon": 0,
    "Jean-Marc Governatori": 0,
    "Mireille Damiano": 1,
  },
  {
    "Theme": "Environnement",
    "Question": "Quelle est la priorité pour améliorer l'environnement ?",
    "Reponse": "végétaliser les écoles primaires",
    "Benoit Kandel": 0,
    "Valéry Sohm": 0,
    "Christian Estrosi": 1,
    "Patrick Allemand": 2,
    "Philippe Vardon": 0,
    "Jean-Marc Governatori": 1,
    "Mireille Damiano": 1,
  },
  {
    "Theme": "Environnement",
    "Question": "Quelle est la priorité pour améliorer l'environnement ?",
    "Reponse": "Interdire l'accès aux véhicules polluants",
    "Benoit Kandel": -2,
    "Valéry Sohm": -2,
    "Christian Estrosi": 2,
    "Patrick Allemand": 1,
    "Philippe Vardon": -2,
    "Jean-Marc Governatori": 2,
    "Mireille Damiano": 2,
  },
  {
    "Theme": "Logement",
    "Question": "Faut-il accroître le nombre de logements sociaux ?",
    "Reponse": "Oui",
    "Benoit Kandel": 0,
    "Valéry Sohm": 0,
    "Christian Estrosi": 0,
    "Patrick Allemand": 2,
    "Philippe Vardon": 0,
    "Jean-Marc Governatori": 0,
    "Mireille Damiano": 2,
    "Estelle Jaquet": 2
  },
  {
    "Theme": "Logement",
    "Question": "Faut-il accroître le nombre de logements sociaux ?",
    "Reponse": "Non",
    "Benoit Kandel": 0,
    "Valéry Sohm": 0,
    "Christian Estrosi": 0,
    "Patrick Allemand": -2,
    "Philippe Vardon": 0,
    "Jean-Marc Governatori": 0,
    "Mireille Damiano": -2,
    "Estelle Jaquet": -2
  },
  {
    "Theme": "Environnement",
    "Question": "Faut-il proposer une alternative végétarienne tous les jours dans les cantines ?",
    "Reponse": "Oui",
    "Benoit Kandel": -2,
    "Valéry Sohm": -2,
    "Christian Estrosi": 2,
    "Patrick Allemand": -2,
    "Philippe Vardon": -2,
    "Jean-Marc Governatori": 2,
    "Mireille Damiano": 2,
  },
  {
    "Theme": "Environnement",
    "Question": "Faut-il proposer une alternative végétarienne tous les jours dans les cantines ?",
    "Reponse": "Non",
    "Benoit Kandel": 2,
    "Valéry Sohm": 2,
    "Christian Estrosi": -2,
    "Patrick Allemand": 2,
    "Philippe Vardon": 2,
    "Jean-Marc Governatori": -2,
    "Mireille Damiano": -2,
  },
  {
    "Theme": "Environnement",
    "Question": "Faut-il limiter la place de la publicité dans l'espace public ?",
    "Reponse": "Oui",
    "Benoit Kandel": 0,
    "Valéry Sohm": 0,
    "Christian Estrosi": 1,
    "Patrick Allemand": 0,
    "Philippe Vardon": 1,
    "Jean-Marc Governatori": 2,
    "Mireille Damiano": 1,
  },
  {
    "Theme": "Environnement",
    "Question": "Faut-il limiter la place de la publicité dans l'espace public ?",
    "Reponse": "Non",
    "Benoit Kandel": 0,
    "Valéry Sohm": 0,
    "Christian Estrosi": -1,
    "Patrick Allemand": 0,
    "Philippe Vardon": -1,
    "Jean-Marc Governatori": -2,
    "Mireille Damiano": -1,
  },

  {
    "Theme": "Ethique",
    "Question": "Le mandat d'un élu municipal devrait être non cumulable et limité dans le temps",
    "Reponse": "Oui",
    "Benoit Kandel": -1,
    "Valéry Sohm": 0,
    "Christian Estrosi": -2,
    "Patrick Allemand": 0,
    "Philippe Vardon": 0,
    "Jean-Marc Governatori": 0,
    "Mireille Damiano": 2,
  },
  {
    "Theme": "Ethique",
    "Question": "Le mandat d'un élu municipal devrait être non cumulable et limité dans le temps",
    "Reponse": "Non",
    "Benoit Kandel": 1,
    "Valéry Sohm":0,
    "Christian Estrosi": 2,
    "Patrick Allemand": 0,
    "Philippe Vardon": 0,
    "Jean-Marc Governatori": 0,
    "Mireille Damiano": -2,
  },
  {
    "Theme": "Ethique",
    "Question": "Un élu ne devrait jamais avoir été condamné dans une affaire qui met en cause sa probité",
    "Reponse": "Oui",
    "Benoit Kandel": 2,
    "Valéry Sohm": 2,
    "Christian Estrosi": 2,
    "Patrick Allemand": 0,
    "Philippe Vardon": 0,
    "Jean-Marc Governatori": 0,
    "Mireille Damiano": 2,
  },
  {
    "Theme": "Ethique",
    "Question": "Un élu ne devrait jamais avoir été condamné dans une affaire qui met en cause sa probité",
    "Reponse": "Non",
    "Benoit Kandel": -2,
    "Valéry Sohm": -2,
    "Christian Estrosi": -2,
    "Patrick Allemand": 0,
    "Philippe Vardon": 0,
    "Jean-Marc Governatori": 0,
    "Mireille Damiano": -2,
  },
  {
    "Theme": "Solidarité",
    "Question": "Pour les seniors, la priorité, c'est...",
    "Reponse": "construire des EHPAD",
    "Benoit Kandel": 0,
    "Valéry Sohm": 0,
    "Christian Estrosi": 0,
    "Patrick Allemand": 2,
    "Philippe Vardon": 0,
    "Jean-Marc Governatori": 0,
    "Mireille Damiano": 2,
  },
  {
    "Theme": "Solidarité",
    "Question": "Pour les seniors, la priorité, c'est...",
    "Reponse": "des maisons de santé",
    "Benoit Kandel": 0,
    "Valéry Sohm": 0,
    "Christian Estrosi": 2,
    "Patrick Allemand": 1,
    "Philippe Vardon": 0,
    "Jean-Marc Governatori": 0,
    "Mireille Damiano": 1,
  },
  {
    "Theme": "Commerce",
    "Question": "Pour protéger le petit commerce faut-il interdire la création de grandes surfaces?",
    "Reponse": "Oui",
    "Benoit Kandel": 1,
    "Valéry Sohm": 0,
    "Christian Estrosi": -2,
    "Patrick Allemand": 2,
    "Philippe Vardon": 2,
    "Jean-Marc Governatori": 0,
    "Mireille Damiano": 0,
  },
  {
    "Theme": "Commerce",
    "Question": "Pour protéger le petit commerce faut-il interdire la création de grandes surfaces?",
    "Reponse": "Non",
    "Benoit Kandel": -1,
    "Valéry Sohm": 0,
    "Christian Estrosi": 2,
    "Patrick Allemand": -2,
    "Philippe Vardon": -2,
    "Jean-Marc Governatori": 0,
    "Mireille Damiano": 0,
  },
    {
    "Theme": "Démocratie",
    "Question": "Faut-il instaurer un référendum d'initiative citoyenne local à Nice ?",
    "Reponse": "Oui",
    "Benoit Kandel": 0,
    "Valéry Sohm": 2,
    "Christian Estrosi": 0,
    "Patrick Allemand": 0,
    "Philippe Vardon": 2,
    "Jean-Marc Governatori": 0,
    "Mireille Damiano": 2,
  },
  {
    "Theme": "Démocratie",
    "Question": "Faut-il instaurer un référendum d'initiative citoyenne local à Nice ?",
    "Reponse": "Non",
    "Benoit Kandel": 0,
    "Valéry Sohm": -2,
    "Christian Estrosi": 0,
    "Patrick Allemand": 0,
    "Philippe Vardon": -2,
    "Jean-Marc Governatori": 0,
    "Mireille Damiano": -2,
  }
];



  var output=[];
  var questions=[];
  var candidats=[];

  for (let i = 0; i < QR.length; i++) {
    questions.push(QR[i].Question);
  }
  var uniq = [...new Set(questions)];

  var tmp_candidats = Object.getOwnPropertyNames(QR[0]);
  for (let i = 0; i < tmp_candidats.length; i++) {
      if(tmp_candidats[i] != "Theme" && tmp_candidats[i] != "Question" && tmp_candidats[i] != "Reponse"){
        candidats.push(tmp_candidats[i]);
      }
  }


  for (let i = 0; i < uniq.length; i++) {
      const question = uniq[i];
      var o = {}
      o.Question = question;
      o.Reponses = []
      for (let j = 0; j < QR.length; j++) {
          const element = QR[j];
          var p = {};
          if(element.Question == question){
            o.Theme = element.Theme;
              p.name = element['Reponse'];
              for (let k = 0; k < candidats.length; k++) {
                  p[candidats[k]] = element[candidats[k]];
              }
              o.Reponses.push(p)
          }
      }
      output.push(o)
  }

 module.exports = output;
